//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SODAPortalMvcApplication.SODAPayPalSerRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrencyCodeType", Namespace="http://schemas.datacontract.org/2004/07/PayPal.PayPalAPIInterfaceService.Model")]
    public enum CurrencyCodeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AFA = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALL = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DZD = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADP = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AOA = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ARS = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AMD = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AWG = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AZM = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BSD = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BHD = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BDT = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BBD = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BYR = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BZD = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BMD = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BTN = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INR = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BOV = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BOB = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BAM = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BWP = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BRL = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BND = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BGL = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BGN = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BIF = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KHR = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CAD = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CVE = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KYD = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XAF = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLF = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLP = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CNY = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COP = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KMF = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CDF = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CRC = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HRK = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUP = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CYP = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CZK = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DKK = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DJF = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOP = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TPE = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ECV = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ECS = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EGP = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SVC = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERN = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EEK = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ETB = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FKP = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FJD = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMD = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GEL = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GHC = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GIP = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GTQ = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GNF = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GWP = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GYD = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HTG = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HNL = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HKD = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HUF = 67,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISK = 68,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IDR = 69,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IRR = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IQD = 71,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ILS = 72,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JMD = 73,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JPY = 74,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JOD = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KZT = 76,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KES = 77,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AUD = 78,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KPW = 79,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KRW = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KWD = 81,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KGS = 82,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LAK = 83,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LVL = 84,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LBP = 85,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LSL = 86,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LRD = 87,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LYD = 88,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CHF = 89,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LTL = 90,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MOP = 91,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MKD = 92,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MGF = 93,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MWK = 94,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MYR = 95,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MVR = 96,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTL = 97,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EUR = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MRO = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MUR = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MXN = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MXV = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MDL = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNT = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XCD = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MZM = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MMK = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZAR = 108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NAD = 109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NPR = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ANG = 111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XPF = 112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NZD = 113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NIO = 114,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NGN = 115,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOK = 116,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OMR = 117,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PKR = 118,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAB = 119,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PGK = 120,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PYG = 121,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PEN = 122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PHP = 123,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLN = 124,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USD = 125,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QAR = 126,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ROL = 127,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RUB = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RUR = 129,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RWF = 130,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SHP = 131,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WST = 132,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STD = 133,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SAR = 134,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SCR = 135,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SLL = 136,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SGD = 137,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SKK = 138,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SIT = 139,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SBD = 140,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SOS = 141,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LKR = 142,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SDD = 143,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SRG = 144,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SZL = 145,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SEK = 146,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SYP = 147,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TWD = 148,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TJS = 149,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TZS = 150,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        THB = 151,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XOF = 152,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TOP = 153,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TTD = 154,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TND = 155,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRY = 156,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TMM = 157,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UGX = 158,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UAH = 159,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AED = 160,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GBP = 161,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USS = 162,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USN = 163,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UYU = 164,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UZS = 165,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VUV = 166,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VEB = 167,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VND = 168,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MAD = 169,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YER = 170,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YUM = 171,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZMK = 172,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZWD = 173,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUSTOMCODE = 174,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecuringProfileDetails", Namespace="http://schemas.datacontract.org/2004/07/SODAwcfService.Models")]
    [System.SerializableAttribute()]
    public partial class RecuringProfileDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<SODAPortalMvcApplication.SODAPayPalSerRef.RecurringPaymentsProfileStatusType> profileStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<SODAPortalMvcApplication.SODAPayPalSerRef.RecurringPaymentsProfileStatusType> profileStatus {
            get {
                return this.profileStatusField;
            }
            set {
                if ((this.profileStatusField.Equals(value) != true)) {
                    this.profileStatusField = value;
                    this.RaisePropertyChanged("profileStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurringPaymentsProfileStatusType", Namespace="http://schemas.datacontract.org/2004/07/PayPal.PayPalAPIInterfaceService.Model")]
    public enum RecurringPaymentsProfileStatusType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACTIVEPROFILE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PENDINGPROFILE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CANCELLEDPROFILE = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EXPIREDPROFILE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUSPENDEDPROFILE = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SODAPayPalSerRef.ISODAPaypalService")]
    public interface ISODAPaypalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/checkout", ReplyAction="http://tempuri.org/ISODAPaypalService/checkoutResponse")]
        string checkout(decimal amt, SODAPortalMvcApplication.SODAPayPalSerRef.CurrencyCodeType cType, string itemName, string itemDesc, string itemURL, string cancelurl, string confirmUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/checkout", ReplyAction="http://tempuri.org/ISODAPaypalService/checkoutResponse")]
        System.Threading.Tasks.Task<string> checkoutAsync(decimal amt, SODAPortalMvcApplication.SODAPayPalSerRef.CurrencyCodeType cType, string itemName, string itemDesc, string itemURL, string cancelurl, string confirmUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/confirmation", ReplyAction="http://tempuri.org/ISODAPaypalService/confirmationResponse")]
        string confirmation(long userid, string payorid, string token, decimal amt, decimal recur_amt, SODAPortalMvcApplication.SODAPayPalSerRef.CurrencyCodeType cType, string itemName, string itemDesc, System.DateTime dateStart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/confirmation", ReplyAction="http://tempuri.org/ISODAPaypalService/confirmationResponse")]
        System.Threading.Tasks.Task<string> confirmationAsync(long userid, string payorid, string token, decimal amt, decimal recur_amt, SODAPortalMvcApplication.SODAPayPalSerRef.CurrencyCodeType cType, string itemName, string itemDesc, System.DateTime dateStart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/cancelSubscription", ReplyAction="http://tempuri.org/ISODAPaypalService/cancelSubscriptionResponse")]
        bool cancelSubscription(long userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/cancelSubscription", ReplyAction="http://tempuri.org/ISODAPaypalService/cancelSubscriptionResponse")]
        System.Threading.Tasks.Task<bool> cancelSubscriptionAsync(long userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/getRecurProfileDetails", ReplyAction="http://tempuri.org/ISODAPaypalService/getRecurProfileDetailsResponse")]
        SODAPortalMvcApplication.SODAPayPalSerRef.RecuringProfileDetails getRecurProfileDetails(long userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/getRecurProfileDetails", ReplyAction="http://tempuri.org/ISODAPaypalService/getRecurProfileDetailsResponse")]
        System.Threading.Tasks.Task<SODAPortalMvcApplication.SODAPayPalSerRef.RecuringProfileDetails> getRecurProfileDetailsAsync(long userid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISODAPaypalServiceChannel : SODAPortalMvcApplication.SODAPayPalSerRef.ISODAPaypalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SODAPaypalServiceClient : System.ServiceModel.ClientBase<SODAPortalMvcApplication.SODAPayPalSerRef.ISODAPaypalService>, SODAPortalMvcApplication.SODAPayPalSerRef.ISODAPaypalService {
        
        public SODAPaypalServiceClient() {
        }
        
        public SODAPaypalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SODAPaypalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SODAPaypalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SODAPaypalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string checkout(decimal amt, SODAPortalMvcApplication.SODAPayPalSerRef.CurrencyCodeType cType, string itemName, string itemDesc, string itemURL, string cancelurl, string confirmUrl) {
            return base.Channel.checkout(amt, cType, itemName, itemDesc, itemURL, cancelurl, confirmUrl);
        }
        
        public System.Threading.Tasks.Task<string> checkoutAsync(decimal amt, SODAPortalMvcApplication.SODAPayPalSerRef.CurrencyCodeType cType, string itemName, string itemDesc, string itemURL, string cancelurl, string confirmUrl) {
            return base.Channel.checkoutAsync(amt, cType, itemName, itemDesc, itemURL, cancelurl, confirmUrl);
        }
        
        public string confirmation(long userid, string payorid, string token, decimal amt, decimal recur_amt, SODAPortalMvcApplication.SODAPayPalSerRef.CurrencyCodeType cType, string itemName, string itemDesc, System.DateTime dateStart) {
            return base.Channel.confirmation(userid, payorid, token, amt, recur_amt, cType, itemName, itemDesc, dateStart);
        }
        
        public System.Threading.Tasks.Task<string> confirmationAsync(long userid, string payorid, string token, decimal amt, decimal recur_amt, SODAPortalMvcApplication.SODAPayPalSerRef.CurrencyCodeType cType, string itemName, string itemDesc, System.DateTime dateStart) {
            return base.Channel.confirmationAsync(userid, payorid, token, amt, recur_amt, cType, itemName, itemDesc, dateStart);
        }
        
        public bool cancelSubscription(long userid) {
            return base.Channel.cancelSubscription(userid);
        }
        
        public System.Threading.Tasks.Task<bool> cancelSubscriptionAsync(long userid) {
            return base.Channel.cancelSubscriptionAsync(userid);
        }
        
        public SODAPortalMvcApplication.SODAPayPalSerRef.RecuringProfileDetails getRecurProfileDetails(long userid) {
            return base.Channel.getRecurProfileDetails(userid);
        }
        
        public System.Threading.Tasks.Task<SODAPortalMvcApplication.SODAPayPalSerRef.RecuringProfileDetails> getRecurProfileDetailsAsync(long userid) {
            return base.Channel.getRecurProfileDetailsAsync(userid);
        }
    }
}
