//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SODAPortalMvcApplication.SODAPayPalSerRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrencyCodeType", Namespace="http://schemas.datacontract.org/2004/07/PayPal.PayPalAPIInterfaceService.Model")]
    public enum CurrencyCodeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AFA = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALL = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DZD = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADP = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AOA = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ARS = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AMD = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AWG = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AZM = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BSD = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BHD = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BDT = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BBD = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BYR = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BZD = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BMD = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BTN = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INR = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BOV = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BOB = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BAM = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BWP = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BRL = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BND = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BGL = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BGN = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BIF = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KHR = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CAD = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CVE = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KYD = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XAF = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLF = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLP = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CNY = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COP = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KMF = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CDF = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CRC = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HRK = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUP = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CYP = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CZK = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DKK = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DJF = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOP = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TPE = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ECV = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ECS = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EGP = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SVC = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERN = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EEK = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ETB = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FKP = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FJD = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMD = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GEL = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GHC = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GIP = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GTQ = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GNF = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GWP = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GYD = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HTG = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HNL = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HKD = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HUF = 67,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISK = 68,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IDR = 69,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IRR = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IQD = 71,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ILS = 72,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JMD = 73,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JPY = 74,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JOD = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KZT = 76,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KES = 77,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AUD = 78,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KPW = 79,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KRW = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KWD = 81,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KGS = 82,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LAK = 83,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LVL = 84,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LBP = 85,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LSL = 86,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LRD = 87,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LYD = 88,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CHF = 89,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LTL = 90,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MOP = 91,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MKD = 92,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MGF = 93,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MWK = 94,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MYR = 95,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MVR = 96,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTL = 97,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EUR = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MRO = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MUR = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MXN = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MXV = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MDL = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNT = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XCD = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MZM = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MMK = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZAR = 108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NAD = 109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NPR = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ANG = 111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XPF = 112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NZD = 113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NIO = 114,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NGN = 115,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOK = 116,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OMR = 117,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PKR = 118,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAB = 119,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PGK = 120,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PYG = 121,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PEN = 122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PHP = 123,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLN = 124,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USD = 125,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QAR = 126,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ROL = 127,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RUB = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RUR = 129,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RWF = 130,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SHP = 131,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WST = 132,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STD = 133,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SAR = 134,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SCR = 135,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SLL = 136,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SGD = 137,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SKK = 138,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SIT = 139,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SBD = 140,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SOS = 141,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LKR = 142,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SDD = 143,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SRG = 144,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SZL = 145,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SEK = 146,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SYP = 147,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TWD = 148,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TJS = 149,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TZS = 150,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        THB = 151,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XOF = 152,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TOP = 153,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TTD = 154,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TND = 155,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRY = 156,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TMM = 157,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UGX = 158,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UAH = 159,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AED = 160,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GBP = 161,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USS = 162,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USN = 163,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UYU = 164,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UZS = 165,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VUV = 166,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VEB = 167,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VND = 168,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MAD = 169,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YER = 170,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YUM = 171,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZMK = 172,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZWD = 173,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUSTOMCODE = 174,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayPalCheckOutModel", Namespace="http://schemas.datacontract.org/2004/07/SODAwcfService.Models")]
    [System.SerializableAttribute()]
    public partial class PayPalCheckOutModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingAgreementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<SODAPortalMvcApplication.SODAPayPalSerRef.CurrencyCodeType> CTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TaxTotalamtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cancelurlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string confirmUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string itemDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string itemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double itemTotalamtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double orderTotalamtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string taxAmtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingAgreement {
            get {
                return this.BillingAgreementField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingAgreementField, value) != true)) {
                    this.BillingAgreementField = value;
                    this.RaisePropertyChanged("BillingAgreement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<SODAPortalMvcApplication.SODAPayPalSerRef.CurrencyCodeType> CType {
            get {
                return this.CTypeField;
            }
            set {
                if ((this.CTypeField.Equals(value) != true)) {
                    this.CTypeField = value;
                    this.RaisePropertyChanged("CType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemAmt {
            get {
                return this.ItemAmtField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemAmtField, value) != true)) {
                    this.ItemAmtField = value;
                    this.RaisePropertyChanged("ItemAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderDesc {
            get {
                return this.OrderDescField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderDescField, value) != true)) {
                    this.OrderDescField = value;
                    this.RaisePropertyChanged("OrderDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TaxTotalamt {
            get {
                return this.TaxTotalamtField;
            }
            set {
                if ((this.TaxTotalamtField.Equals(value) != true)) {
                    this.TaxTotalamtField = value;
                    this.RaisePropertyChanged("TaxTotalamt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cancelurl {
            get {
                return this.cancelurlField;
            }
            set {
                if ((object.ReferenceEquals(this.cancelurlField, value) != true)) {
                    this.cancelurlField = value;
                    this.RaisePropertyChanged("cancelurl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string confirmUrl {
            get {
                return this.confirmUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.confirmUrlField, value) != true)) {
                    this.confirmUrlField = value;
                    this.RaisePropertyChanged("confirmUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string itemDesc {
            get {
                return this.itemDescField;
            }
            set {
                if ((object.ReferenceEquals(this.itemDescField, value) != true)) {
                    this.itemDescField = value;
                    this.RaisePropertyChanged("itemDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string itemName {
            get {
                return this.itemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.itemNameField, value) != true)) {
                    this.itemNameField = value;
                    this.RaisePropertyChanged("itemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double itemTotalamt {
            get {
                return this.itemTotalamtField;
            }
            set {
                if ((this.itemTotalamtField.Equals(value) != true)) {
                    this.itemTotalamtField = value;
                    this.RaisePropertyChanged("itemTotalamt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double orderTotalamt {
            get {
                return this.orderTotalamtField;
            }
            set {
                if ((this.orderTotalamtField.Equals(value) != true)) {
                    this.orderTotalamtField = value;
                    this.RaisePropertyChanged("orderTotalamt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string taxAmt {
            get {
                return this.taxAmtField;
            }
            set {
                if ((object.ReferenceEquals(this.taxAmtField, value) != true)) {
                    this.taxAmtField = value;
                    this.RaisePropertyChanged("taxAmt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayPalConfirmModel", Namespace="http://schemas.datacontract.org/2004/07/SODAwcfService.Models")]
    [System.SerializableAttribute()]
    public partial class PayPalConfirmModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BillingFrequencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PaymenytAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SalesCodeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaxAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<SODAPortalMvcApplication.SODAPayPalSerRef.CurrencyCodeType> cTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string payoridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string schedDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> useridField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BillingFrequency {
            get {
                return this.BillingFrequencyField;
            }
            set {
                if ((this.BillingFrequencyField.Equals(value) != true)) {
                    this.BillingFrequencyField = value;
                    this.RaisePropertyChanged("BillingFrequency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PaymenytAmt {
            get {
                return this.PaymenytAmtField;
            }
            set {
                if ((this.PaymenytAmtField.Equals(value) != true)) {
                    this.PaymenytAmtField = value;
                    this.RaisePropertyChanged("PaymenytAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qty {
            get {
                return this.QtyField;
            }
            set {
                if ((this.QtyField.Equals(value) != true)) {
                    this.QtyField = value;
                    this.RaisePropertyChanged("Qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SalesCodeId {
            get {
                return this.SalesCodeIdField;
            }
            set {
                if ((this.SalesCodeIdField.Equals(value) != true)) {
                    this.SalesCodeIdField = value;
                    this.RaisePropertyChanged("SalesCodeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxAmt {
            get {
                return this.TaxAmtField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxAmtField, value) != true)) {
                    this.TaxAmtField = value;
                    this.RaisePropertyChanged("TaxAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<SODAPortalMvcApplication.SODAPayPalSerRef.CurrencyCodeType> cType {
            get {
                return this.cTypeField;
            }
            set {
                if ((this.cTypeField.Equals(value) != true)) {
                    this.cTypeField = value;
                    this.RaisePropertyChanged("cType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateStart {
            get {
                return this.dateStartField;
            }
            set {
                if ((this.dateStartField.Equals(value) != true)) {
                    this.dateStartField = value;
                    this.RaisePropertyChanged("dateStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payorid {
            get {
                return this.payoridField;
            }
            set {
                if ((object.ReferenceEquals(this.payoridField, value) != true)) {
                    this.payoridField = value;
                    this.RaisePropertyChanged("payorid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string schedDesc {
            get {
                return this.schedDescField;
            }
            set {
                if ((object.ReferenceEquals(this.schedDescField, value) != true)) {
                    this.schedDescField = value;
                    this.RaisePropertyChanged("schedDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> userid {
            get {
                return this.useridField;
            }
            set {
                if ((this.useridField.Equals(value) != true)) {
                    this.useridField = value;
                    this.RaisePropertyChanged("userid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecuringProfileDetails", Namespace="http://schemas.datacontract.org/2004/07/SODAwcfService.Models")]
    [System.SerializableAttribute()]
    public partial class RecuringProfileDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<SODAPortalMvcApplication.SODAPayPalSerRef.RecurringPaymentsProfileStatusType> profileStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<SODAPortalMvcApplication.SODAPayPalSerRef.RecurringPaymentsProfileStatusType> profileStatus {
            get {
                return this.profileStatusField;
            }
            set {
                if ((this.profileStatusField.Equals(value) != true)) {
                    this.profileStatusField = value;
                    this.RaisePropertyChanged("profileStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurringPaymentsProfileStatusType", Namespace="http://schemas.datacontract.org/2004/07/PayPal.PayPalAPIInterfaceService.Model")]
    public enum RecurringPaymentsProfileStatusType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACTIVEPROFILE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PENDINGPROFILE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CANCELLEDPROFILE = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EXPIREDPROFILE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUSPENDEDPROFILE = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayPalTrans", Namespace="http://schemas.datacontract.org/2004/07/SODAwcfService.Models")]
    [System.SerializableAttribute()]
    public partial class PayPalTrans : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ECTransIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RPPProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SalesCodeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateLogField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ECTransID {
            get {
                return this.ECTransIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ECTransIDField, value) != true)) {
                    this.ECTransIDField = value;
                    this.RaisePropertyChanged("ECTransID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qty {
            get {
                return this.QtyField;
            }
            set {
                if ((this.QtyField.Equals(value) != true)) {
                    this.QtyField = value;
                    this.RaisePropertyChanged("Qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RPPProfile {
            get {
                return this.RPPProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.RPPProfileField, value) != true)) {
                    this.RPPProfileField = value;
                    this.RaisePropertyChanged("RPPProfile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SalesCodeID {
            get {
                return this.SalesCodeIDField;
            }
            set {
                if ((this.SalesCodeIDField.Equals(value) != true)) {
                    this.SalesCodeIDField = value;
                    this.RaisePropertyChanged("SalesCodeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalAmt {
            get {
                return this.TotalAmtField;
            }
            set {
                if ((this.TotalAmtField.Equals(value) != true)) {
                    this.TotalAmtField = value;
                    this.RaisePropertyChanged("TotalAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateLog {
            get {
                return this.dateLogField;
            }
            set {
                if ((this.dateLogField.Equals(value) != true)) {
                    this.dateLogField = value;
                    this.RaisePropertyChanged("dateLog");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SODAPayPalSerRef.ISODAPaypalService")]
    public interface ISODAPaypalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/checkout", ReplyAction="http://tempuri.org/ISODAPaypalService/checkoutResponse")]
        string checkout(decimal amt, SODAPortalMvcApplication.SODAPayPalSerRef.CurrencyCodeType cType, string itemName, string itemDesc, string itemURL, string cancelurl, string confirmUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/checkout", ReplyAction="http://tempuri.org/ISODAPaypalService/checkoutResponse")]
        System.Threading.Tasks.Task<string> checkoutAsync(decimal amt, SODAPortalMvcApplication.SODAPayPalSerRef.CurrencyCodeType cType, string itemName, string itemDesc, string itemURL, string cancelurl, string confirmUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/checkoutModel", ReplyAction="http://tempuri.org/ISODAPaypalService/checkoutModelResponse")]
        string checkoutModel(SODAPortalMvcApplication.SODAPayPalSerRef.PayPalCheckOutModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/checkoutModel", ReplyAction="http://tempuri.org/ISODAPaypalService/checkoutModelResponse")]
        System.Threading.Tasks.Task<string> checkoutModelAsync(SODAPortalMvcApplication.SODAPayPalSerRef.PayPalCheckOutModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/confirmation", ReplyAction="http://tempuri.org/ISODAPaypalService/confirmationResponse")]
        string confirmation(long userid, string payorid, string token, decimal amt, decimal recur_amt, SODAPortalMvcApplication.SODAPayPalSerRef.CurrencyCodeType cType, string itemName, string itemDesc, System.DateTime dateStart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/confirmation", ReplyAction="http://tempuri.org/ISODAPaypalService/confirmationResponse")]
        System.Threading.Tasks.Task<string> confirmationAsync(long userid, string payorid, string token, decimal amt, decimal recur_amt, SODAPortalMvcApplication.SODAPayPalSerRef.CurrencyCodeType cType, string itemName, string itemDesc, System.DateTime dateStart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/confirmationModel", ReplyAction="http://tempuri.org/ISODAPaypalService/confirmationModelResponse")]
        string confirmationModel(SODAPortalMvcApplication.SODAPayPalSerRef.PayPalConfirmModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/confirmationModel", ReplyAction="http://tempuri.org/ISODAPaypalService/confirmationModelResponse")]
        System.Threading.Tasks.Task<string> confirmationModelAsync(SODAPortalMvcApplication.SODAPayPalSerRef.PayPalConfirmModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/cancelSubscription", ReplyAction="http://tempuri.org/ISODAPaypalService/cancelSubscriptionResponse")]
        bool cancelSubscription(string transid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/cancelSubscription", ReplyAction="http://tempuri.org/ISODAPaypalService/cancelSubscriptionResponse")]
        System.Threading.Tasks.Task<bool> cancelSubscriptionAsync(string transid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/getRecurProfileDetails", ReplyAction="http://tempuri.org/ISODAPaypalService/getRecurProfileDetailsResponse")]
        SODAPortalMvcApplication.SODAPayPalSerRef.RecuringProfileDetails getRecurProfileDetails(long userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/getRecurProfileDetails", ReplyAction="http://tempuri.org/ISODAPaypalService/getRecurProfileDetailsResponse")]
        System.Threading.Tasks.Task<SODAPortalMvcApplication.SODAPayPalSerRef.RecuringProfileDetails> getRecurProfileDetailsAsync(long userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/getRecurProfileDetailsByTransID", ReplyAction="http://tempuri.org/ISODAPaypalService/getRecurProfileDetailsByTransIDResponse")]
        SODAPortalMvcApplication.SODAPayPalSerRef.RecuringProfileDetails getRecurProfileDetailsByTransID(string TransID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/getRecurProfileDetailsByTransID", ReplyAction="http://tempuri.org/ISODAPaypalService/getRecurProfileDetailsByTransIDResponse")]
        System.Threading.Tasks.Task<SODAPortalMvcApplication.SODAPayPalSerRef.RecuringProfileDetails> getRecurProfileDetailsByTransIDAsync(string TransID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/getPayPalTrans", ReplyAction="http://tempuri.org/ISODAPaypalService/getPayPalTransResponse")]
        SODAPortalMvcApplication.SODAPayPalSerRef.PayPalTrans[] getPayPalTrans();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/getPayPalTrans", ReplyAction="http://tempuri.org/ISODAPaypalService/getPayPalTransResponse")]
        System.Threading.Tasks.Task<SODAPortalMvcApplication.SODAPayPalSerRef.PayPalTrans[]> getPayPalTransAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/initPayPalAccountSettings", ReplyAction="http://tempuri.org/ISODAPaypalService/initPayPalAccountSettingsResponse")]
        bool initPayPalAccountSettings(int regionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISODAPaypalService/initPayPalAccountSettings", ReplyAction="http://tempuri.org/ISODAPaypalService/initPayPalAccountSettingsResponse")]
        System.Threading.Tasks.Task<bool> initPayPalAccountSettingsAsync(int regionID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISODAPaypalServiceChannel : SODAPortalMvcApplication.SODAPayPalSerRef.ISODAPaypalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SODAPaypalServiceClient : System.ServiceModel.ClientBase<SODAPortalMvcApplication.SODAPayPalSerRef.ISODAPaypalService>, SODAPortalMvcApplication.SODAPayPalSerRef.ISODAPaypalService {
        
        public SODAPaypalServiceClient() {
        }
        
        public SODAPaypalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SODAPaypalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SODAPaypalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SODAPaypalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string checkout(decimal amt, SODAPortalMvcApplication.SODAPayPalSerRef.CurrencyCodeType cType, string itemName, string itemDesc, string itemURL, string cancelurl, string confirmUrl) {
            return base.Channel.checkout(amt, cType, itemName, itemDesc, itemURL, cancelurl, confirmUrl);
        }
        
        public System.Threading.Tasks.Task<string> checkoutAsync(decimal amt, SODAPortalMvcApplication.SODAPayPalSerRef.CurrencyCodeType cType, string itemName, string itemDesc, string itemURL, string cancelurl, string confirmUrl) {
            return base.Channel.checkoutAsync(amt, cType, itemName, itemDesc, itemURL, cancelurl, confirmUrl);
        }
        
        public string checkoutModel(SODAPortalMvcApplication.SODAPayPalSerRef.PayPalCheckOutModel model) {
            return base.Channel.checkoutModel(model);
        }
        
        public System.Threading.Tasks.Task<string> checkoutModelAsync(SODAPortalMvcApplication.SODAPayPalSerRef.PayPalCheckOutModel model) {
            return base.Channel.checkoutModelAsync(model);
        }
        
        public string confirmation(long userid, string payorid, string token, decimal amt, decimal recur_amt, SODAPortalMvcApplication.SODAPayPalSerRef.CurrencyCodeType cType, string itemName, string itemDesc, System.DateTime dateStart) {
            return base.Channel.confirmation(userid, payorid, token, amt, recur_amt, cType, itemName, itemDesc, dateStart);
        }
        
        public System.Threading.Tasks.Task<string> confirmationAsync(long userid, string payorid, string token, decimal amt, decimal recur_amt, SODAPortalMvcApplication.SODAPayPalSerRef.CurrencyCodeType cType, string itemName, string itemDesc, System.DateTime dateStart) {
            return base.Channel.confirmationAsync(userid, payorid, token, amt, recur_amt, cType, itemName, itemDesc, dateStart);
        }
        
        public string confirmationModel(SODAPortalMvcApplication.SODAPayPalSerRef.PayPalConfirmModel model) {
            return base.Channel.confirmationModel(model);
        }
        
        public System.Threading.Tasks.Task<string> confirmationModelAsync(SODAPortalMvcApplication.SODAPayPalSerRef.PayPalConfirmModel model) {
            return base.Channel.confirmationModelAsync(model);
        }
        
        public bool cancelSubscription(string transid) {
            return base.Channel.cancelSubscription(transid);
        }
        
        public System.Threading.Tasks.Task<bool> cancelSubscriptionAsync(string transid) {
            return base.Channel.cancelSubscriptionAsync(transid);
        }
        
        public SODAPortalMvcApplication.SODAPayPalSerRef.RecuringProfileDetails getRecurProfileDetails(long userid) {
            return base.Channel.getRecurProfileDetails(userid);
        }
        
        public System.Threading.Tasks.Task<SODAPortalMvcApplication.SODAPayPalSerRef.RecuringProfileDetails> getRecurProfileDetailsAsync(long userid) {
            return base.Channel.getRecurProfileDetailsAsync(userid);
        }
        
        public SODAPortalMvcApplication.SODAPayPalSerRef.RecuringProfileDetails getRecurProfileDetailsByTransID(string TransID) {
            return base.Channel.getRecurProfileDetailsByTransID(TransID);
        }
        
        public System.Threading.Tasks.Task<SODAPortalMvcApplication.SODAPayPalSerRef.RecuringProfileDetails> getRecurProfileDetailsByTransIDAsync(string TransID) {
            return base.Channel.getRecurProfileDetailsByTransIDAsync(TransID);
        }
        
        public SODAPortalMvcApplication.SODAPayPalSerRef.PayPalTrans[] getPayPalTrans() {
            return base.Channel.getPayPalTrans();
        }
        
        public System.Threading.Tasks.Task<SODAPortalMvcApplication.SODAPayPalSerRef.PayPalTrans[]> getPayPalTransAsync() {
            return base.Channel.getPayPalTransAsync();
        }
        
        public bool initPayPalAccountSettings(int regionID) {
            return base.Channel.initPayPalAccountSettings(regionID);
        }
        
        public System.Threading.Tasks.Task<bool> initPayPalAccountSettingsAsync(int regionID) {
            return base.Channel.initPayPalAccountSettingsAsync(regionID);
        }
    }
}
