//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SODAwcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Customers = new HashSet<Customer>();
            this.SalesPersons = new HashSet<SalesPerson>();
        }
    
        public long Id { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Role { get; set; }
        public short Status { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Gender { get; set; }
        public string ContactNo { get; set; }
        public string Company { get; set; }
        public Nullable<System.DateTime> DateLogin { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public bool EmailVerify { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<SalesPerson> SalesPersons { get; set; }
    }
}
