//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SODAwcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class chapter
    {
        public long Id { get; set; }
        public Nullable<long> SpecID { get; set; }
        public string ChapterName { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
    
        public virtual Specific Specific { get; set; }
    }
}
