//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SODAwcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentDef
    {
        public string PageCode { get; set; }
        public string SectionName { get; set; }
        public string Type { get; set; }
        public string Value { get; set; }
    
        public virtual Page Page { get; set; }
    }
}
