//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SODAwcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long Id { get; set; }
        public string Sales_Code { get; set; }
        public System.DateTime DatePurchase { get; set; }
        public System.DateTime DateSubscriptionEnd { get; set; }
        public long UserId { get; set; }
    }
}
