//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SODAwcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.SalesPersons = new HashSet<SalesPerson>();
            this.PriceTables = new HashSet<PriceTable>();
        }
    
        public int Id { get; set; }
        public string RegionName { get; set; }
    
        public virtual ICollection<SalesPerson> SalesPersons { get; set; }
        public virtual ICollection<PriceTable> PriceTables { get; set; }
    }
}
