//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SODAwcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPerson
    {
        public SalesPerson()
        {
            this.SalesCodes = new HashSet<SalesCode>();
        }
    
        public int Id { get; set; }
        public string Sales_Code { get; set; }
        public long UserId { get; set; }
        public int RegionId { get; set; }
    
        public virtual ICollection<SalesCode> SalesCodes { get; set; }
    }
}
