//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SODAwcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesCode
    {
        public long Id { get; set; }
        public Nullable<int> SalesPersonID { get; set; }
        public string Sales_Code { get; set; }
        public decimal Discount { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    
        public virtual SalesPerson SalesPerson { get; set; }
    }
}
