//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SODAwcfService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SodaDBEntities1 : DbContext
    {
        public SodaDBEntities1()
            : base("name=SodaDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<Specific> Specifics { get; set; }
        public virtual DbSet<ContentDef> ContentDefs { get; set; }
        public virtual DbSet<chapter> chapters { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
    }
}
