//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SODAwcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specific
    {
        public Specific()
        {
            this.Specific1 = new HashSet<Specific>();
            this.Specifics = new HashSet<Specific>();
        }
    
        public long Id { get; set; }
        public long CategoryID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string VideoURL { get; set; }
        public string ImageURL { get; set; }
        public string Metatags { get; set; }
        public string bg_img { get; set; }
        public string TitleCode { get; set; }
        public string Overview { get; set; }
        public string PageTitle { get; set; }
        public string Meta_Desc { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Specific> Specific1 { get; set; }
        public virtual ICollection<Specific> Specifics { get; set; }
    }
}
