//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSMvcApplication.CatListingServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/SODAwcfService.Models")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BG_IMGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Banner_IMGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMG_URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetatagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OverviewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PageTitileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BG_IMG {
            get {
                return this.BG_IMGField;
            }
            set {
                if ((object.ReferenceEquals(this.BG_IMGField, value) != true)) {
                    this.BG_IMGField = value;
                    this.RaisePropertyChanged("BG_IMG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Banner_IMG {
            get {
                return this.Banner_IMGField;
            }
            set {
                if ((object.ReferenceEquals(this.Banner_IMGField, value) != true)) {
                    this.Banner_IMGField = value;
                    this.RaisePropertyChanged("Banner_IMG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMG_URL {
            get {
                return this.IMG_URLField;
            }
            set {
                if ((object.ReferenceEquals(this.IMG_URLField, value) != true)) {
                    this.IMG_URLField = value;
                    this.RaisePropertyChanged("IMG_URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaDesc {
            get {
                return this.MetaDescField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaDescField, value) != true)) {
                    this.MetaDescField = value;
                    this.RaisePropertyChanged("MetaDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Metatags {
            get {
                return this.MetatagsField;
            }
            set {
                if ((object.ReferenceEquals(this.MetatagsField, value) != true)) {
                    this.MetatagsField = value;
                    this.RaisePropertyChanged("Metatags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Overview {
            get {
                return this.OverviewField;
            }
            set {
                if ((object.ReferenceEquals(this.OverviewField, value) != true)) {
                    this.OverviewField = value;
                    this.RaisePropertyChanged("Overview");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PageTitile {
            get {
                return this.PageTitileField;
            }
            set {
                if ((object.ReferenceEquals(this.PageTitileField, value) != true)) {
                    this.PageTitileField = value;
                    this.RaisePropertyChanged("PageTitile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Specific", Namespace="http://schemas.datacontract.org/2004/07/SODAwcfService.Models")]
    [System.SerializableAttribute()]
    public partial class Specific : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BG_ImgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetatagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OverviewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PageTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VideoURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BG_Img {
            get {
                return this.BG_ImgField;
            }
            set {
                if ((object.ReferenceEquals(this.BG_ImgField, value) != true)) {
                    this.BG_ImgField = value;
                    this.RaisePropertyChanged("BG_Img");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURL {
            get {
                return this.ImageURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLField, value) != true)) {
                    this.ImageURLField = value;
                    this.RaisePropertyChanged("ImageURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaDesc {
            get {
                return this.MetaDescField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaDescField, value) != true)) {
                    this.MetaDescField = value;
                    this.RaisePropertyChanged("MetaDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Metatags {
            get {
                return this.MetatagsField;
            }
            set {
                if ((object.ReferenceEquals(this.MetatagsField, value) != true)) {
                    this.MetatagsField = value;
                    this.RaisePropertyChanged("Metatags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Overview {
            get {
                return this.OverviewField;
            }
            set {
                if ((object.ReferenceEquals(this.OverviewField, value) != true)) {
                    this.OverviewField = value;
                    this.RaisePropertyChanged("Overview");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PageTitle {
            get {
                return this.PageTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.PageTitleField, value) != true)) {
                    this.PageTitleField = value;
                    this.RaisePropertyChanged("PageTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TitleCode {
            get {
                return this.TitleCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleCodeField, value) != true)) {
                    this.TitleCodeField = value;
                    this.RaisePropertyChanged("TitleCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VideoURL {
            get {
                return this.VideoURLField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoURLField, value) != true)) {
                    this.VideoURLField = value;
                    this.RaisePropertyChanged("VideoURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CatListingServiceReference.ICatListingService")]
    public interface ICatListingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/add_Category", ReplyAction="http://tempuri.org/ICatListingService/add_CategoryResponse")]
        int add_Category(CMSMvcApplication.CatListingServiceReference.Category category_new);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/update_Category", ReplyAction="http://tempuri.org/ICatListingService/update_CategoryResponse")]
        int update_Category(CMSMvcApplication.CatListingServiceReference.Category category_new);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/delete_Category", ReplyAction="http://tempuri.org/ICatListingService/delete_CategoryResponse")]
        int delete_Category(long CategoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/get_Category", ReplyAction="http://tempuri.org/ICatListingService/get_CategoryResponse")]
        CMSMvcApplication.CatListingServiceReference.Category[] get_Category(long CategoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/get_Categories", ReplyAction="http://tempuri.org/ICatListingService/get_CategoriesResponse")]
        CMSMvcApplication.CatListingServiceReference.Category[] get_Categories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/add_Specific", ReplyAction="http://tempuri.org/ICatListingService/add_SpecificResponse")]
        int add_Specific(CMSMvcApplication.CatListingServiceReference.Specific specific_new);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/update_Specific", ReplyAction="http://tempuri.org/ICatListingService/update_SpecificResponse")]
        int update_Specific(CMSMvcApplication.CatListingServiceReference.Specific specific_new);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/delete_Specific", ReplyAction="http://tempuri.org/ICatListingService/delete_SpecificResponse")]
        int delete_Specific(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/getSpecificByID", ReplyAction="http://tempuri.org/ICatListingService/getSpecificByIDResponse")]
        CMSMvcApplication.CatListingServiceReference.Specific[] getSpecificByID(long ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/getSpecificByCatID", ReplyAction="http://tempuri.org/ICatListingService/getSpecificByCatIDResponse")]
        CMSMvcApplication.CatListingServiceReference.Specific[] getSpecificByCatID(long CatID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/Authenticate", ReplyAction="http://tempuri.org/ICatListingService/AuthenticateResponse")]
        bool Authenticate(string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/getRelatedByID", ReplyAction="http://tempuri.org/ICatListingService/getRelatedByIDResponse")]
        CMSMvcApplication.CatListingServiceReference.Specific[] getRelatedByID(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/get", ReplyAction="http://tempuri.org/ICatListingService/getResponse")]
        CMSMvcApplication.CatListingServiceReference.Specific[] get();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICatListingServiceChannel : CMSMvcApplication.CatListingServiceReference.ICatListingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatListingServiceClient : System.ServiceModel.ClientBase<CMSMvcApplication.CatListingServiceReference.ICatListingService>, CMSMvcApplication.CatListingServiceReference.ICatListingService {
        
        public CatListingServiceClient() {
        }
        
        public CatListingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatListingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatListingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatListingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int add_Category(CMSMvcApplication.CatListingServiceReference.Category category_new) {
            return base.Channel.add_Category(category_new);
        }
        
        public int update_Category(CMSMvcApplication.CatListingServiceReference.Category category_new) {
            return base.Channel.update_Category(category_new);
        }
        
        public int delete_Category(long CategoryID) {
            return base.Channel.delete_Category(CategoryID);
        }
        
        public CMSMvcApplication.CatListingServiceReference.Category[] get_Category(long CategoryID) {
            return base.Channel.get_Category(CategoryID);
        }
        
        public CMSMvcApplication.CatListingServiceReference.Category[] get_Categories() {
            return base.Channel.get_Categories();
        }
        
        public int add_Specific(CMSMvcApplication.CatListingServiceReference.Specific specific_new) {
            return base.Channel.add_Specific(specific_new);
        }
        
        public int update_Specific(CMSMvcApplication.CatListingServiceReference.Specific specific_new) {
            return base.Channel.update_Specific(specific_new);
        }
        
        public int delete_Specific(long id) {
            return base.Channel.delete_Specific(id);
        }
        
        public CMSMvcApplication.CatListingServiceReference.Specific[] getSpecificByID(long ID) {
            return base.Channel.getSpecificByID(ID);
        }
        
        public CMSMvcApplication.CatListingServiceReference.Specific[] getSpecificByCatID(long CatID) {
            return base.Channel.getSpecificByCatID(CatID);
        }
        
        public bool Authenticate(string password) {
            return base.Channel.Authenticate(password);
        }
        
        public CMSMvcApplication.CatListingServiceReference.Specific[] getRelatedByID(long id) {
            return base.Channel.getRelatedByID(id);
        }
        
        public CMSMvcApplication.CatListingServiceReference.Specific[] get() {
            return base.Channel.get();
        }
    }
}
