//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SODAMvcApplication.CategoriesServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/SODAwcfService.Models")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BG_IMGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Banner_IMGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMG_URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetatagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OverviewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PageTitileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BG_IMG {
            get {
                return this.BG_IMGField;
            }
            set {
                if ((object.ReferenceEquals(this.BG_IMGField, value) != true)) {
                    this.BG_IMGField = value;
                    this.RaisePropertyChanged("BG_IMG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Banner_IMG {
            get {
                return this.Banner_IMGField;
            }
            set {
                if ((object.ReferenceEquals(this.Banner_IMGField, value) != true)) {
                    this.Banner_IMGField = value;
                    this.RaisePropertyChanged("Banner_IMG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMG_URL {
            get {
                return this.IMG_URLField;
            }
            set {
                if ((object.ReferenceEquals(this.IMG_URLField, value) != true)) {
                    this.IMG_URLField = value;
                    this.RaisePropertyChanged("IMG_URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaDesc {
            get {
                return this.MetaDescField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaDescField, value) != true)) {
                    this.MetaDescField = value;
                    this.RaisePropertyChanged("MetaDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Metatags {
            get {
                return this.MetatagsField;
            }
            set {
                if ((object.ReferenceEquals(this.MetatagsField, value) != true)) {
                    this.MetatagsField = value;
                    this.RaisePropertyChanged("Metatags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Overview {
            get {
                return this.OverviewField;
            }
            set {
                if ((object.ReferenceEquals(this.OverviewField, value) != true)) {
                    this.OverviewField = value;
                    this.RaisePropertyChanged("Overview");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PageTitile {
            get {
                return this.PageTitileField;
            }
            set {
                if ((object.ReferenceEquals(this.PageTitileField, value) != true)) {
                    this.PageTitileField = value;
                    this.RaisePropertyChanged("PageTitile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Specific", Namespace="http://schemas.datacontract.org/2004/07/SODAwcfService.Models")]
    [System.SerializableAttribute()]
    public partial class Specific : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BG_ImgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateQuestionAnswerChangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DownloadlableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InDiscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetatagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OverviewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PageTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VideoURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isDOwnloadNewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalChaptersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Approved {
            get {
                return this.ApprovedField;
            }
            set {
                if ((this.ApprovedField.Equals(value) != true)) {
                    this.ApprovedField = value;
                    this.RaisePropertyChanged("Approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BG_Img {
            get {
                return this.BG_ImgField;
            }
            set {
                if ((object.ReferenceEquals(this.BG_ImgField, value) != true)) {
                    this.BG_ImgField = value;
                    this.RaisePropertyChanged("BG_Img");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateQuestionAnswerChange {
            get {
                return this.DateQuestionAnswerChangeField;
            }
            set {
                if ((this.DateQuestionAnswerChangeField.Equals(value) != true)) {
                    this.DateQuestionAnswerChangeField = value;
                    this.RaisePropertyChanged("DateQuestionAnswerChange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Downloadlable {
            get {
                return this.DownloadlableField;
            }
            set {
                if ((this.DownloadlableField.Equals(value) != true)) {
                    this.DownloadlableField = value;
                    this.RaisePropertyChanged("Downloadlable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURL {
            get {
                return this.ImageURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLField, value) != true)) {
                    this.ImageURLField = value;
                    this.RaisePropertyChanged("ImageURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InDisc {
            get {
                return this.InDiscField;
            }
            set {
                if ((this.InDiscField.Equals(value) != true)) {
                    this.InDiscField = value;
                    this.RaisePropertyChanged("InDisc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaDesc {
            get {
                return this.MetaDescField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaDescField, value) != true)) {
                    this.MetaDescField = value;
                    this.RaisePropertyChanged("MetaDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Metatags {
            get {
                return this.MetatagsField;
            }
            set {
                if ((object.ReferenceEquals(this.MetatagsField, value) != true)) {
                    this.MetatagsField = value;
                    this.RaisePropertyChanged("Metatags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Overview {
            get {
                return this.OverviewField;
            }
            set {
                if ((object.ReferenceEquals(this.OverviewField, value) != true)) {
                    this.OverviewField = value;
                    this.RaisePropertyChanged("Overview");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PageTitle {
            get {
                return this.PageTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.PageTitleField, value) != true)) {
                    this.PageTitleField = value;
                    this.RaisePropertyChanged("PageTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TitleCode {
            get {
                return this.TitleCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleCodeField, value) != true)) {
                    this.TitleCodeField = value;
                    this.RaisePropertyChanged("TitleCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VideoURL {
            get {
                return this.VideoURLField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoURLField, value) != true)) {
                    this.VideoURLField = value;
                    this.RaisePropertyChanged("VideoURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isDOwnloadNews {
            get {
                return this.isDOwnloadNewsField;
            }
            set {
                if ((this.isDOwnloadNewsField.Equals(value) != true)) {
                    this.isDOwnloadNewsField = value;
                    this.RaisePropertyChanged("isDOwnloadNews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan time {
            get {
                return this.timeField;
            }
            set {
                if ((this.timeField.Equals(value) != true)) {
                    this.timeField = value;
                    this.RaisePropertyChanged("time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalChapters {
            get {
                return this.totalChaptersField;
            }
            set {
                if ((this.totalChaptersField.Equals(value) != true)) {
                    this.totalChaptersField = value;
                    this.RaisePropertyChanged("totalChapters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chapter", Namespace="http://schemas.datacontract.org/2004/07/SODAwcfService.Models")]
    [System.SerializableAttribute()]
    public partial class Chapter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChapterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> SpecIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> timeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChapterName {
            get {
                return this.ChapterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ChapterNameField, value) != true)) {
                    this.ChapterNameField = value;
                    this.RaisePropertyChanged("ChapterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> SpecID {
            get {
                return this.SpecIDField;
            }
            set {
                if ((this.SpecIDField.Equals(value) != true)) {
                    this.SpecIDField = value;
                    this.RaisePropertyChanged("SpecID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> time {
            get {
                return this.timeField;
            }
            set {
                if ((this.timeField.Equals(value) != true)) {
                    this.timeField = value;
                    this.RaisePropertyChanged("time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Topic", Namespace="http://schemas.datacontract.org/2004/07/SODAwcfService.Models")]
    [System.SerializableAttribute()]
    public partial class Topic : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> SpecIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> SpecId {
            get {
                return this.SpecIdField;
            }
            set {
                if ((this.SpecIdField.Equals(value) != true)) {
                    this.SpecIdField = value;
                    this.RaisePropertyChanged("SpecId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryAssignment", Namespace="http://schemas.datacontract.org/2004/07/SODAwcfService.Models")]
    [System.SerializableAttribute()]
    public partial class CategoryAssignment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SpecIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SpecID {
            get {
                return this.SpecIDField;
            }
            set {
                if ((this.SpecIDField.Equals(value) != true)) {
                    this.SpecIDField = value;
                    this.RaisePropertyChanged("SpecID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CategoriesServiceReference.ICatListingService")]
    public interface ICatListingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/add_Category", ReplyAction="http://tempuri.org/ICatListingService/add_CategoryResponse")]
        int add_Category(SODAMvcApplication.CategoriesServiceReference.Category category_new);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/update_Category", ReplyAction="http://tempuri.org/ICatListingService/update_CategoryResponse")]
        int update_Category(SODAMvcApplication.CategoriesServiceReference.Category category_new);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/delete_Category", ReplyAction="http://tempuri.org/ICatListingService/delete_CategoryResponse")]
        int delete_Category(long CategoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/get_Category", ReplyAction="http://tempuri.org/ICatListingService/get_CategoryResponse")]
        SODAMvcApplication.CategoriesServiceReference.Category[] get_Category(long CategoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/get_Categories", ReplyAction="http://tempuri.org/ICatListingService/get_CategoriesResponse")]
        SODAMvcApplication.CategoriesServiceReference.Category[] get_Categories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/add_Specific", ReplyAction="http://tempuri.org/ICatListingService/add_SpecificResponse")]
        int add_Specific(SODAMvcApplication.CategoriesServiceReference.Specific specific_new);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/update_Specific", ReplyAction="http://tempuri.org/ICatListingService/update_SpecificResponse")]
        int update_Specific(SODAMvcApplication.CategoriesServiceReference.Specific specific_new);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/delete_Specific", ReplyAction="http://tempuri.org/ICatListingService/delete_SpecificResponse")]
        int delete_Specific(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/getSpecificByID", ReplyAction="http://tempuri.org/ICatListingService/getSpecificByIDResponse")]
        SODAMvcApplication.CategoriesServiceReference.Specific[] getSpecificByID(long ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/getSpecificByCatID", ReplyAction="http://tempuri.org/ICatListingService/getSpecificByCatIDResponse")]
        SODAMvcApplication.CategoriesServiceReference.Specific[] getSpecificByCatID(long CatID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/Authenticate", ReplyAction="http://tempuri.org/ICatListingService/AuthenticateResponse")]
        bool Authenticate(string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/getRelatedByID", ReplyAction="http://tempuri.org/ICatListingService/getRelatedByIDResponse")]
        SODAMvcApplication.CategoriesServiceReference.Specific[] getRelatedByID(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/get", ReplyAction="http://tempuri.org/ICatListingService/getResponse")]
        SODAMvcApplication.CategoriesServiceReference.Specific[] get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/addChapter", ReplyAction="http://tempuri.org/ICatListingService/addChapterResponse")]
        int addChapter(long specID, string name, System.TimeSpan time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/getChapter", ReplyAction="http://tempuri.org/ICatListingService/getChapterResponse")]
        SODAMvcApplication.CategoriesServiceReference.Chapter[] getChapter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/updateChapter", ReplyAction="http://tempuri.org/ICatListingService/updateChapterResponse")]
        int updateChapter(SODAMvcApplication.CategoriesServiceReference.Chapter chapter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/deleteChapter", ReplyAction="http://tempuri.org/ICatListingService/deleteChapterResponse")]
        int deleteChapter(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/addTopic", ReplyAction="http://tempuri.org/ICatListingService/addTopicResponse")]
        int addTopic(long specID, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/getTopics", ReplyAction="http://tempuri.org/ICatListingService/getTopicsResponse")]
        SODAMvcApplication.CategoriesServiceReference.Topic[] getTopics();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/updateTopic", ReplyAction="http://tempuri.org/ICatListingService/updateTopicResponse")]
        int updateTopic(SODAMvcApplication.CategoriesServiceReference.Topic topic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/deleteTopic", ReplyAction="http://tempuri.org/ICatListingService/deleteTopicResponse")]
        int deleteTopic(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/getCatAssign", ReplyAction="http://tempuri.org/ICatListingService/getCatAssignResponse")]
        SODAMvcApplication.CategoriesServiceReference.CategoryAssignment[] getCatAssign();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/addCatAssign", ReplyAction="http://tempuri.org/ICatListingService/addCatAssignResponse")]
        int addCatAssign(long specId, long catId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/updateCatAssign", ReplyAction="http://tempuri.org/ICatListingService/updateCatAssignResponse")]
        int updateCatAssign(long specId, long catId, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatListingService/deleteCatAssign", ReplyAction="http://tempuri.org/ICatListingService/deleteCatAssignResponse")]
        int deleteCatAssign(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICatListingServiceChannel : SODAMvcApplication.CategoriesServiceReference.ICatListingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatListingServiceClient : System.ServiceModel.ClientBase<SODAMvcApplication.CategoriesServiceReference.ICatListingService>, SODAMvcApplication.CategoriesServiceReference.ICatListingService {
        
        public CatListingServiceClient() {
        }
        
        public CatListingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatListingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatListingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatListingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int add_Category(SODAMvcApplication.CategoriesServiceReference.Category category_new) {
            return base.Channel.add_Category(category_new);
        }
        
        public int update_Category(SODAMvcApplication.CategoriesServiceReference.Category category_new) {
            return base.Channel.update_Category(category_new);
        }
        
        public int delete_Category(long CategoryID) {
            return base.Channel.delete_Category(CategoryID);
        }
        
        public SODAMvcApplication.CategoriesServiceReference.Category[] get_Category(long CategoryID) {
            return base.Channel.get_Category(CategoryID);
        }
        
        public SODAMvcApplication.CategoriesServiceReference.Category[] get_Categories() {
            return base.Channel.get_Categories();
        }
        
        public int add_Specific(SODAMvcApplication.CategoriesServiceReference.Specific specific_new) {
            return base.Channel.add_Specific(specific_new);
        }
        
        public int update_Specific(SODAMvcApplication.CategoriesServiceReference.Specific specific_new) {
            return base.Channel.update_Specific(specific_new);
        }
        
        public int delete_Specific(long id) {
            return base.Channel.delete_Specific(id);
        }
        
        public SODAMvcApplication.CategoriesServiceReference.Specific[] getSpecificByID(long ID) {
            return base.Channel.getSpecificByID(ID);
        }
        
        public SODAMvcApplication.CategoriesServiceReference.Specific[] getSpecificByCatID(long CatID) {
            return base.Channel.getSpecificByCatID(CatID);
        }
        
        public bool Authenticate(string password) {
            return base.Channel.Authenticate(password);
        }
        
        public SODAMvcApplication.CategoriesServiceReference.Specific[] getRelatedByID(long id) {
            return base.Channel.getRelatedByID(id);
        }
        
        public SODAMvcApplication.CategoriesServiceReference.Specific[] get() {
            return base.Channel.get();
        }
        
        public int addChapter(long specID, string name, System.TimeSpan time) {
            return base.Channel.addChapter(specID, name, time);
        }
        
        public SODAMvcApplication.CategoriesServiceReference.Chapter[] getChapter() {
            return base.Channel.getChapter();
        }
        
        public int updateChapter(SODAMvcApplication.CategoriesServiceReference.Chapter chapter) {
            return base.Channel.updateChapter(chapter);
        }
        
        public int deleteChapter(long id) {
            return base.Channel.deleteChapter(id);
        }
        
        public int addTopic(long specID, string name) {
            return base.Channel.addTopic(specID, name);
        }
        
        public SODAMvcApplication.CategoriesServiceReference.Topic[] getTopics() {
            return base.Channel.getTopics();
        }
        
        public int updateTopic(SODAMvcApplication.CategoriesServiceReference.Topic topic) {
            return base.Channel.updateTopic(topic);
        }
        
        public int deleteTopic(long id) {
            return base.Channel.deleteTopic(id);
        }
        
        public SODAMvcApplication.CategoriesServiceReference.CategoryAssignment[] getCatAssign() {
            return base.Channel.getCatAssign();
        }
        
        public int addCatAssign(long specId, long catId) {
            return base.Channel.addCatAssign(specId, catId);
        }
        
        public int updateCatAssign(long specId, long catId, int Id) {
            return base.Channel.updateCatAssign(specId, catId, Id);
        }
        
        public int deleteCatAssign(int Id) {
            return base.Channel.deleteCatAssign(Id);
        }
    }
}
